name: 'setup-renv'
description: 'Action to setup renv and install R dependencies in the lockfile'
author: 'patrik.beka@powerex.io'
inputs:
  working-dir:
    description: 'Working directory with source codes and renv.lock file'
    required: true
  renv-version:
    description: 'Version of renv package'
    required: false
    default: 0.14.0
  # TODO setup via env var - GITHUB_PAT
  personal-access-token:
    description: 'Github access token for installing packages from private repositories'
    required: false
    default: "personal-access-token"
  cache-version:
    description: 'Version of renv cache'
    required: false
    default: v3

runs:
  using: "composite"
  steps:
      - name: Check if lockfile exist
        run: |
          FILE=${{ inputs.working-dir }}/renv.lock

          if [ -f "$FILE" ]; then
              echo "$FILE found."
          else
              echo "$FILE does not exist."
              exit 1
          fi
        shell: bash

      # TODO install via remotes
      - name: Install renv
        run: |
          install.packages("https://cran.r-project.org/src/contrib/Archive/renv/renv_${{ inputs.renv-version }}.tar.gz", repos=NULL, type="source")
        shell: Rscript {0}

      - name: Set up renv dir as env variable
        run: |
          renv_global_lib_path <- renv:::renv_libpaths_resolve(library = NULL)[1]

          # set global lib dir
          system(paste0("echo 'GLOBAL_LIB_DIR=", renv_global_lib_path, "' >> $GITHUB_ENV"))

          # set renv directory as env variable for cache
          system(paste0("echo 'RENV_LIB_DIR=", "${{ inputs.working-dir }}/renv", "' >> $GITHUB_ENV"))
        shell: Rscript {0}

      - name: Always upload local cache
        uses: pat-s/always-upload-cache@v2.1.5
        with:
          path: "${{ env.RENV_LIB_DIR }}"
          key: local-${{ runner.os }}-${{ inputs.working-dir }}-renv-${{ inputs.cache-version }}-${{ hashFiles('**/renv.lock') }}
          restore-keys: local-${{ runner.os }}-${{ inputs.working-dir }}-renv-${{ inputs.cache-version }}

      - name: Always upload global cache
        uses: pat-s/always-upload-cache@v2.1.5
        with:
          path: "${{ env.GLOBAL_LIB_DIR }}"
          key: global-${{ runner.os }}-${{ inputs.working-dir }}-renv-${{ inputs.cache-version }}-${{ hashFiles('**/renv.lock') }}
          restore-keys: global-${{ runner.os }}-${{ inputs.working-dir }}-renv-${{ inputs.cache-version }}

      - name: Install dependencies from lockfile
        run: |
          # set personal access token for private repositories
          Sys.setenv(GITHUB_PAT = "${{ inputs.personal-access-token }}")

          # restore to global lib
          print(paste0("installing to lib: ", renv:::renv_libpaths_resolve(library = NULL)))
          renv::restore(project = "${{ inputs.working-dir }}")

          # activate renv, restore to local renv dir
          renv::activate(project = "${{ inputs.working-dir }}")
          print(paste0("installing to lib: ", renv:::renv_libpaths_resolve(library = NULL)))

          renv::restore(project = "${{ inputs.working-dir }}")

          renv::isolate(project = "${{ inputs.working-dir }}")
          list.files(path = "${{ inputs.working-dir }}")
          list.files(path = "${{ inputs.working-dir }}/renv")
        shell: Rscript {0}

      - name: List installed packages
        run: |
          ls -la "${{ env.RENV_LIB_DIR }}/library/R-4.0/x86_64-pc-linux-gnu"
        shell: bash
