name: 'setup-renv'
description: 'Action to setup renv and install R dependencies in the lockfile'
author: 'patrik.beka@powerex.io'
inputs:
  working-dir:
    description: 'Working directory with source codes and renv.lock file'
    required: true
  renv-version:
    description: 'Version of renv package'
    required: false
    default: 0.13.0

runs:
  using: "composite"
  steps:
      - name: Check if lockfile exist
        run: |
          FILE=${{ inputs.working-dir }}/renv.lock

          if [ -f "$FILE" ]; then
              echo "$FILE found."
          else
              echo "$FILE does not exist."
              exit 1
          fi
        shell: bash

      - name: Install renv
        run: |
          install.packages("https://cran.r-project.org/src/contrib/Archive/renv/renv_${{ inputs.renv-version }}.tar.gz", repos=NULL, type="source")
        shell: Rscript {0}

      - name: Always upload cache
        uses: pat-s/always-upload-cache@v2.1.5
        with:
          path: "${{ inputs.working-dir }}/renv"
          key: local-${{ runner.os }}-${{ inputs.working-dir }}-renv-hashFiles(${{ inputs.working-dir }}/renv.lock)
          restore-keys: local-${{ runner.os }}-${{ inputs.working-dir }}-renv-

      - name: Install dependencies from lockfile
        run: |
          renv::activate(project = "${{ inputs.working-dir }}")
          renv::restore(project = "${{ inputs.working-dir }}")
        shell: Rscript {0}

      - name: List installed packages
        run: |
          ls -la "${{ inputs.working-dir }}/renv"
        shell: bash
