name: 'setup-renv'
description: 'Action to setup renv and install R dependencies in the lockfile'
author: 'patrik.beka@powerex.io'
inputs:
  working-dir:
    description: 'Working directory with source codes and renv.lock file'
    required: true

runs:
  using: "composite"
  steps:

      # TODO
      # check work dir
      # check renv.lock
      # renv version

      - name: Check if lockfile exist
        run: |
          FILE=${{ inputs.working-dir }}/renv.lock

          if [ -f "$FILE" ]; then
              echo "$FILE found."
          else
              echo "$FILE does not exist."
              exit 1
          fi
        shell: bash

      - name: Install renv
        run: |
          install.packages("https://cran.r-project.org/src/contrib/Archive/renv/renv_0.13.0.tar.gz", repos=NULL, type="source")
        shell: Rscript {0}

      - name: Install dependencies from lockfile
        run: renv::restore()
        shell: Rscript {0}

      - name: Restore Renv package cache
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-
