name: 'setup-renv'
description: 'Action to setup renv and install R dependencies in the lockfile'
author: 'patrik.beka@powerex.io'
inputs:
  working-dir:
    description: 'Working directory with source codes and renv.lock file'
    required: true
  renv-version:
    description: 'Version of renv package'
    required: false
    default: 0.17.3
  cache-version:
    description: 'Version of renv cache'
    required: false
    default: v3

runs:
  using: "composite"
  steps:
  
      - name: Check if lockfile exist
        run: |
          FILE=${{ inputs.working-dir }}/renv.lock

          if [ -f "$FILE" ]; then
              echo "$FILE found."
          else
              echo "$FILE does not exist."
              exit 1
          fi
        shell: bash

      - name: Install renv
        run: |
          # install remotes package -> used for install specific renv version from github
          if (require("remotes") == FALSE) {
            install.packages("remotes")
          }

          remotes::install_github("rstudio/renv@${{ inputs.renv-version }}", upgrade = "never")
        shell: Rscript {0}

      - name: Set up renv dir as env variable
        run: |
          renv_global_lib_path <- renv:::renv_libpaths_resolve(library = NULL)[1]
          cat("Global Library Path: ", renv_global_lib_path, "\n")
    
          # set global lib dir
          system(paste0("echo 'GLOBAL_LIB_DIR=", renv_global_lib_path, "' >> $GITHUB_ENV"))
    
          # set renv directory as env variable for cache
          system(paste0("echo 'RENV_LIB_DIR=", "${{ inputs.working-dir }}/renv", "' >> $GITHUB_ENV"))
    
          # Checking permissions for directories
          cat("Checking permissions for directories:\n")
          system("ls -ld $GLOBAL_LIB_DIR")
          system("ls -ld $RENV_LIB_DIR")
        shell: Rscript {0}

      - name: Always upload local cache
        uses: pat-s/always-upload-cache@v3.0.11
        with:
          path: "${{ env.RENV_LIB_DIR }}"
          key: local-${{ runner.os }}-${{ inputs.working-dir }}-renv-${{ inputs.cache-version }}-${{ hashFiles('**/renv.lock') }}
          restore-keys: local-${{ runner.os }}-${{ inputs.working-dir }}-renv-${{ inputs.cache-version }}

      - name: Always upload global cache
        uses: pat-s/always-upload-cache@v3.0.11
        with:
          path: "${{ env.GLOBAL_LIB_DIR }}"
          key: global-${{ runner.os }}-${{ inputs.working-dir }}-renv-${{ inputs.cache-version }}-${{ hashFiles('**/renv.lock') }}
          restore-keys: global-${{ runner.os }}-${{ inputs.working-dir }}-renv-${{ inputs.cache-version }}

      - name: Install dependencies from lockfile
        run: |
          # Print current .libPaths()
          cat("Current .libPaths():\n")
          print(.libPaths())

          # restore to global lib
          print(paste0("installing to lib: ", renv:::renv_libpaths_resolve(library = NULL)))
          renv::restore(project = "${{ inputs.working-dir }}")

          # activate renv, restore to local renv dir
          renv::activate(project = "${{ inputs.working-dir }}")

          # Print updated .libPaths()
          cat("Updated .libPaths():\n")
          print(.libPaths())

          renv::restore(project = "${{ inputs.working-dir }}")

          # isolate and deactivate renv
          renv::isolate(project = "${{ inputs.working-dir }}")
          renv::deactivate(project = "${{ inputs.working-dir }}")
          
          # list installed packages in local renv
          list.files(path = "${{ inputs.working-dir }}")
          list.files(path = "${{ inputs.working-dir }}/renv")
          
        shell: Rscript {0}


      #debug 
      - name: Check root working directory
        run: |
          echo "Inspecting the root working directory content:"
          ls -la "${{ inputs.working-dir }}"
        shell: bash
    
      - name: Check RENV_LIB_DIR content
        run: |
          echo "Inspecting RENV_LIB_DIR:"
          if [ -d "${{ env.RENV_LIB_DIR }}" ]; then
            ls -la "${{ env.RENV_LIB_DIR }}"
          else
            echo "RENV_LIB_DIR does not exist!"
          fi
        shell: bash
    
      - name: List installed packages in renv
        run: |
          echo "Trying to find and list renv library content:"
          if [ -d "${{ env.RENV_LIB_DIR }}/library/" ]; then
            find "${{ env.RENV_LIB_DIR }}/library/" -maxdepth 3 -type d -ls
          else
            echo "Directory ${env.RENV_LIB_DIR}/library/ does not exist!"
          fi
        shell: bash
    
      - name: Recursively explore from root if renv folder is not found
        if: failure() # This step will only run if the previous steps failed
        run: |
          echo "Recursively exploring directory from root to find renv folder:"
          find "${{ inputs.working-dir }}" -type d -name "renv" -ls
        shell: bash

      - name: List installed packages in renv
        run: |
          find "${{ env.RENV_LIB_DIR }}/library/" -maxdepth 3 -type d -ls
        shell: bash
        
      - name: List installed packages in global library dir
        run: |
          find "${{ env.GLOBAL_LIB_DIR }}/" -maxdepth 3 -type d -ls
        shell: bash
