name: 'devtools-test-package'
description: 'Action for testing package via devtools'
author: 'patrik.beka@powerex.io'
inputs:
  package-dir:
    description: 'Package directory'
    required: true
  activate-renv:
    description: 'Boolean flag - activate if tested package is using renv'
    required: false
    default: FALSE
  devtools-version:
    description: 'Version of devtools package'
    required: false
    default: 2.4.2

runs:
  using: "composite"
  steps:
    - name: Run tests
      run: |
        # check if true - github returns defaults as lowercase
        if (toupper("${{ inputs.activate-renv }}") == "TRUE") {
          print("project uses renv - activating, make sure environment is restored before running this step!")

          renv::activate(project = "${{ inputs.package-dir }}")
        }

        # install devtools - needs to be in current r session because of renv
        if ("devtools" %in% rownames(installed.packages()) && packageVersion("devtools") == "${{ inputs.devtools-version }}") {
          print("devtools in version: ${{ inputs.devtools-version }} already installed")
        } else {
          install.packages("https://cran.r-project.org/src/contrib/Archive/devtools/devtools_${{ inputs.devtools-version }}.tar.gz", dependencies="Imports", repos=NULL, type="source")
        }

        devtools::test(pkg = "${{ inputs.package-dir }}", reporter = testthat::JunitReporter$new(file = "junit_result.xml"), stop_on_failure = FALSE)
      shell: Rscript {0}

    - name: Publish Test Results
      uses: mikepenz/action-junit-report@v2
      with:
        report_paths: '${{ inputs.package-dir }}/**/*.xml'
        fail_on_failure: true
